### ISSUE TITLE
Simplify repos by merging items into Guidelines repo

### ISSUE THREAD

**Issue by dbarr99** [SDMX-SWG/Members-and-Administration#1]

**Comment by brainwasher** [comment]
Deleted repo SDMX-SWG/Frequency

**Comment by brainwasher** [comment]
Moved business case document from SDMX-SWG/Business-Case repo to SDMX-SWG/Guidelines repo
Deleted SDMX-SWG/Business-Case repo

**Comment by brainwasher** [comment]
Deleted repo SDMX-SWG/Structural-Modelling
